### ISSUE TITLE
add to benchmarks

### ISSUE THREAD

**Issue by karaul** [roznet/fit-benchmarks#1]
Hello,

It's not an issue, just an addtition  for your table.

fitplotter (javascript)
https://github.com/karaul/fitplotter

sample.fit : 2.71 
large.fit: 24.15 sec

ThinkPad X1 Carbon Ultrabook, 0-th gen  (2012), 
Intel Core i5-3427U Processor (3M Cache, up to 2.80 GHz)
8gb 

Regards
Evgeny

**Comment by roznet** [comment]
Thanks. Happy to. 

Could should share sample code to run the benchmarks in javascript? I am not very familiar, can it be done from command line or need some webpage? 
I could add it to the repo and run it on the same machine for fair comparison.

**Comment by karaul** [comment]
It can be done in any browser, provided one installed fitplotter. Installation is simple: clone or zip fitplotter folder. In any simple text editor open src/main.js and find the line  

fitParser.parse(e.target.result, function (error, data) {

at the monent it is line no: 549. This entrance to parse fit file.

put there:

var t0=performance.now(); // initilaize timer
console.log('t0: ', t0); // output timer value
fitParser.parse(e.target.result, function (error, data) { // the line you just found

Then find closing "}" of the function fitParser.parse, it is the line no: 633 at the moment. Put after  closing "}" three lines

} // what you found
var t1=performance.now(); // stop timer
console.log('t1: ', t1); 
console.log('t1-t0: ', t1-t0);  // performance time

Then, open index.html by your browser, inside the browser open browser's console, and finally open the *.fit file by the fitplotter. In the browser console you will see the performance time.

**Comment by karaul** [comment]
I made a commit to include timing for fit-file parsing. The only what is needed is to open browser's console.

Also, I found that the performance is dependent whether browser is busy at the moment or not.

**Comment by roznet** [comment]
thanks! I wrote my first javascript! got it working from command line with node.
added to the library + credit to you
